name: VocalHeat
options:
  bundleIdPrefix: com.krisenterprisesllc
  deploymentTarget:
    iOS: 15.0
  developmentLanguage: en

settings:
  MARKETING_VERSION: "1.0"
  CURRENT_PROJECT_VERSION: "1"
  SWIFT_VERSION: "5.7"
  IPHONEOS_DEPLOYMENT_TARGET: "15.0"

targets:
  VocalHeat:
    type: application
    platform: iOS
    sources:
      - path: VocalHeat/VocalHeat
        excludes:
          - "*.md"
    info:
      path: VocalHeat/VocalHeat/Info.plist
      properties:
        CFBundleDisplayName: VocalHeat
        CFBundleName: $(PRODUCT_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        LSRequiresIPhoneOS: true
        NSMicrophoneUsageDescription: "VocalHeat needs microphone access to record and analyze your singing voice."
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: true
        UIApplicationSupportsIndirectInputEvents: true
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.krisenterprisesllc.VocalHeat
      INFOPLIST_FILE: VocalHeat/VocalHeat/Info.plist
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
      SWIFT_VERSION: "5.7"
      TARGETED_DEVICE_FAMILY: "1,2"
    dependencies:
      - framework: Accelerate.framework
      - framework: AVFoundation.framework
      - framework: SwiftUI.framework
        implicit: true
      - framework: Combine.framework
        implicit: true
